### ISSUE TITLE
java.io.IOException

### ISSUE THREAD

**Issue by developerAS2** [joergrech/KickstartWithBootstrap#10]
On running the generate-all for a domain class, we get this exception in the console. 

"java.io.IOException: Cannot run program "git": CreateProcess error=2, The system cannot find the file specified"

Let me know, if you need any more details.

On a side note, great plugin! i was just looking for something to kickstart

**Comment by joergrech** [comment]
Thanks for the tip! The problem was that I printed the result of a catched Exception (The script _Events.gsp tried to get a version number from GIT - and you did not have GIT installed!). I corrected this and uploaded a new version into the Grails plugin repository (0.6.1).

**Comment by developerAS2** [comment]
Tested! Resolved.
