### ISSUE TITLE
Suggestion - Rather than an issue

### ISSUE THREAD

**Issue by developerAS2** [joergrech/KickstartWithBootstrap#11]
I think excellent work has gone into this plugin but just extending the though, how good it will be to provide an option for the logged in user to change the theme to suit their preferences and color tone? 

Looking forward to this, whenever it is incorporated.

**Comment by joergrech** [comment]
Good idea, I have a similar technique used in another project where the user can switch between different version (via Less) of Bootstrap. I try to include this into the next version. I'm not sure if the user should switch the "skin" but I think the admin should have the option.

**Comment by developerAS2** [comment]
Well, its user experience, as a user i want to see skimmed or differently organized web page. Also, that adds to the aesthetic appeal. But, again getting it in the scope of this plugin is debatable.

**Comment by developerAS2** [comment]
How good is the api to support mobile browsers? RWD?

**Comment by joergrech** [comment]
Regarding User-changeable Skins: You might want to look at the Skinnable plugin - http://grails.org/plugin/skinnable

Regarding REST: That is on my list but you can use the JSON-based REST plugin: http://grails.org/plugin/json-rest-api that can expose all or only parts of your domain models.

I don't know what you mean with RWD. Real World Data? Read / Writeable Data?

**Comment by developerAS2** [comment]
Hi, thanks for the suggestions, i'll surely check them out.

I was talking about the responsive web designing aspect. http://en.wikipedia.org/wiki/Responsive_Web_Design
