### ISSUE TITLE
resources plugin support

### ISSUE THREAD

**Issue by thomasbittermann** [joergrech/KickstartWithBootstrap#13]
Are you already working on this?

**Comment by joergrech** [comment]
No, not yet.

**Comment by retokiefer** [comment]
I would second that

**Comment by joergrech** [comment]
I just published the 0.8 version of Kickstart with Less support. It uses the lesscss-resource plugin to generate two variants of Bootstrap (the original and one called "Cyborg") from the less files under /web-inf/less. During runtime the skin switcher (unter Config (the cog icon) in the NavBar) can be used to switch between them. 

I hope that helps you - feel free to give me feedback.
