### ISSUE TITLE
bs:datePicker displays the default date with the previous month instead of the current

### ISSUE THREAD

**Issue by omixer** [joergrech/KickstartWithBootstrap#14]
The month in java calendar is zero based (http://docs.oracle.com/javase/6/docs/api/java/util/Calendar.html#MONTH) while the html implementation is 1 based  (http://tools.ietf.org/html/rfc3339#section-5.6)
The way bs:datePicker is implemented doesn't take this into account and thus the default date is always 
a month behind!

**Comment by joergrech** [comment]
Thanks for the tip - the taglib is now corrected.
