### ISSUE TITLE
Missing UrlMappings.groovy in the plugin zip file - version 0.8.0

### ISSUE THREAD

**Issue by sguimont** [joergrech/KickstartWithBootstrap#16]
When executing the grails kickstart command, the script try to copy the file UrlMappings.groovy from the plugins source folder but the file is missing.

It's look like when releasing the plugin the file was skipped from the plugin zip file.

It will be very interesing that you put the github link from your grails plugins page, this way it will be more faster to everyone to get the missing file or to be able to look more closely the plugin code.

A big thank you for your work!  I like the idea :-)

**Comment by joergrech** [comment]
Many thanks for the tip. During development it never showed as I used it as an inline plugin but the packaging script does exclude some artefacts from the resulting zip file (see "Notes on excluded Artefacts" in section http://grails.org/doc/latest/guide/plugins.html#creatingAndInstallingPlugins). 

The version 0.8.1 should fix the problem.
