### ISSUE TITLE
0.8.1 grails prod war fails

### ISSUE THREAD

**Issue by zorrme** [joergrech/KickstartWithBootstrap#17]
1. grails prod war fails to run.
2. Property birthday must be a valid Date error on using datepicker.

**Comment by joergrech** [comment]
Hi, sorry I missed to copy the resources.groovy in conf/spring.

Short fix: add the following line to resources.groovy (within beans={}):
    customPropertyEditorRegistrar(CustomDateEditorRegistrar)

I will correct this in version 0.8.3
