### ISSUE TITLE
use of less

### ISSUE THREAD

**Issue by simonckenyon** [joergrech/KickstartWithBootstrap#2]
it would be good if this used the less versions of the stylesheets

**Comment by joergrech** [comment]
I just published the 0.8 version of Kickstart with Less support. It uses the lesscss-resource plugin to generate two variants of Bootstrap (the original and one called "Cyborg") from the less files under /web-inf/less. During runtime the skin switcher (unter Config (the cog icon) in the NavBar) can be used to switch between them.

I hope that helps you - feel free to give me feedback.
