### ISSUE TITLE
Resources not working in PROD mode

### ISSUE THREAD

**Issue by piizei** [joergrech/KickstartWithBootstrap#23]
image resources are not working with PROD mode or PAAS deployment (clound foundry). If I comment out KickstartResources.groovy skin definitions without less, then it works in PROD with run-war, but not in PAAS. Prod  tries to load images from /APP/images/frontpage/bs-docs-twitter-github.png and PAAS /images/frontpage/bs-docs-twitter-github.png (cloud foundry install apps in ROOT context, so it works right). 
If you can point out problem, I can make the fix.

**Comment by bieniek** [comment]
Same problem, could you prepare temporary fix ?

**Comment by joergrech** [comment]
Should be resolved now in version 0.8.9. Michael Duergner found the problem which was that the resource plugin now requires the plugin's name to fetch resources such as images.
