### ISSUE TITLE
CustomDateEditorRegistrar only supports US style date

### ISSUE THREAD

**Issue by scowling** [joergrech/KickstartWithBootstrap#25]
Can you allow for more than one format of date in the custom editor. ie. "dd/MM/yyyy"

Or failing that, explain how I can override it?

**Comment by joergrech** [comment]
Have you tested this with a newer version (0.8.7 and higher)? You can set the format in the I18N files (this is a new feature of Grails since 2.0 or 2.1) like this: 

default.date.format = yyyy-MM-dd

or 

default.date.format = dd. MM. yyyy

**Comment by scowling** [comment]
I'm on holidays until mid January, I'll try when I get back in the office.
Thanks
Steve

**Comment by joergrech** [comment]
Assumed fixed
