### ISSUE TITLE
No such property: TimeCategory (minor, suggested fix)

### ISSUE THREAD

**Issue by bronoman** [joergrech/KickstartWithBootstrap#3]
### Environment

Win7 Home Premium
JDK 1.7.0_01
Grails 2.0.0
KickstartWithBootstrap Plugin 0.5.4
### Symptoms

When starting a new application (here called: boot3) and installing the KickstartWithBootstrap Plugin, the following errors are shown (homepage and console) when calling the homepage of the application:
### Console Output

home.index: [controller:home, action:index]
| Error 2012-02-15 00:11:17,720 ["http-bio-8080"-exec-2] ERROR errors.GrailsExceptionResolver  - MissingPropertyException occurred when processing req
uest: [GET] /boot3/
No such property: TimeCategory for class: kickstart.KickstartFilters. Stacktrace follows:
Message: No such property: TimeCategory for class: kickstart.KickstartFilters
    Line | Method
->>   16 | doCall    in kickstart.KickstartFilters$_closure1_closure2_closure4$$ENOv49Kf
|   1110 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    603 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run       in java.lang.Thread
### Suggested Fix

(already tested, seems to work fine)
in file \grails-app\conf\kickstart.groovy
insert the following after line 1:
import groovy.time.*

**Comment by joergrech** [comment]
Many thanks for your work. I fixed it and uploaded to Github but could not publish it to the Grails portal (Currently, I experience some technical difficulties with the release plugin). I hope it will be available on the Grails Portal tomorrow.

**Comment by bronoman** [comment]
Jörg: it is published now and works like a charm! Thank you very much.
I really like the automation Grails brings to software development, so I just created a small command line tool to automate the entire process of creating a Grails App using Kickstart with Bootstrap. 
Take a look at: https://github.com/bronoman/kickstarter-tool 
Please feel free to fork and include it with your plugin distribution, if you like.

**Comment by joergrech** [comment]
Hi Bronoman
  sorry for the late answer.

The script is really interesting as it connects with another idea/vision of
mine about an (Grails) App Configurator (similar to a car configurator).
The output of the configurator would look similar to your script and state
where to create the app, which plugins are to be installed, how to glue
them together, etc. I' currently writing on a small blog post to describe
my idea and will come back to you.

Many thanks for your script,
Joerg

On Wed, Feb 15, 2012 at 15:17, bronoman <
reply@reply.github.com

> wrote:
> 
> Jrg: it is published now and works like a charm! Thank you very much.
> I really like the automation Grails brings to software development, so I
> just created a small command line tool to automate the entire process of
> creating a Grails App using Kickstart with Bootstrap.
> Take a look at: https://github.com/bronoman/kickstarter-tool
> Please feel free to fork and include it with your plugin distribution, if
> you like.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/joergrech/KickstartWithBootstrap/issues/3#issuecomment-3980889

## 

_Dr. Jrg Rech_
Kriegsstr. 164
76133 Karlsruhe, Germany

E-Mail:  joerg.rech@gmail.com
Twitter:  http://twitter.com/joergrech
Web:  http://www.joerg-rech.com
Xing: http://www.xing.com/profile/Joerg_Rech/
LinkedIn: http://www.linkedin.com/in/joergrech
