### ISSUE TITLE
App stats and version in application.properties

### ISSUE THREAD

**Issue by sdidit** [joergrech/KickstartWithBootstrap#30]
When I use this plugin, I get all kinds of unwanted statistics and version info in my application.properties file. I understand this is by design, but is there any way to disable it?

**Comment by joergrech** [comment]
This is currently a feature of Kickstart. The stats (as well as the build numbers) are generated before every compile in the script _Events.groovy (see "eventCompileStart"). 

To remove them you need to remove the script file or the Kickstart plugin itself (Kickstart was initially designed to just inject code and scripts into the project - But I haven't tested it lately). Depending on your version and preferences you might want to copy the HomeController, the Taglib, KickstartFilters, dependencies from the BuildConfig, I18N codes etc. from the Kickstart plugin (within your personal ~/.grails directory) into your project.

If I find time I will extract them into an individual plugin(s).

**Comment by sdidit** [comment]
Thanks for the tip, I'll copy the files.
