### ISSUE TITLE
Stuck at "Retrieving stats about the application"

### ISSUE THREAD

**Issue by starryknight64** [joergrech/KickstartWithBootstrap#32]
When I run my GRAILS application for the first time with Kickstart, it runs fine. The WAR gets loaded, the web site pops up, everything's great.
If I shut it down and try to run it again, it gets stuck at "Retrieving stats about the application"

i.e.
    Listening for transport dt_socket at address: 5005
    | Loading Grails 2.2.0
    | Configuring classpath
    | Configuring classpath.
    | Environment set to development
    | Environment set to development.
    | Environment set to development..
    | Environment set to development...
    | Environment set to development....
    | Environment set to development.....
    | Packaging Grails application
    | Retrieving stats about the application

**Comment by starryknight64** [comment]
I was able to work around it by commenting out lines 108-123 of _Events.groovy in the "plugins\kickstart-with-bootstrap-0.8.9\scripts: folder:

```
/*def out = cmd.execute().text
out.split("\n").each { line ->
    if (line =~ /^[\s]*\|[A-Za-z\s]*\|[0-9\s]*\|[0-9\s]*.*$/) {
        def tokenSplit = line.split("\\|")
        def files   = tokenSplit[2].trim()
        def loc     = tokenSplit[3].trim()
        def name    = tokenSplit[1].trim().replace(' ', '_')

        def filesID = 'app.stats.'+name+'.files'
        def locID   = 'app.stats.'+name+'.loc'
        metadata.put(filesID, files)
        metadata.put(locID, loc)

        stats << [tokenSplit[1].trim(), tokenSplit[2].trim(), tokenSplit[3].trim()]
    }
}*/
```

**Comment by joergrech** [comment]
Which operating system are you using? It looks like the command "grails stats" isn't executed correctly - however it is strange that it works the first time. 
Can you execute "grails stats" on the command line and give me the output? Maybe the output changes and cannot be parsed anymore.

**Comment by starryknight64** [comment]
My operating system is Windows 7 64-bit. I'm also running Grails 2.2, in case that matters at all (I realize it's technically not supported, but so far, this is the only hiccup).

Here's my output from grails stats:

```
| Environment set to development....

    +----------------------+-------+-------+
    | Name                 | Files |  LOC  |
    +----------------------+-------+-------+
    | Controllers          |    19 |  1546 |
    | Domain Classes       |    16 |   260 |
    | Unit Tests           |    30 |  1830 |
    +----------------------+-------+-------+
    | Totals               |    65 |  3636 |
    +----------------------+-------+-------+
```

**Comment by joergrech** [comment]
Strange, I have the same setup. The output of your "grails stats" looks normal to me - if it is parsed the first time it should also be parsed thereafter. 

Nevertheless, I integrated a configuration setting to disable the calculation of these metrics or the build numbers. It's described in the section "Configuration" of the documentation at https://github.com/joergrech/KickstartWithBootstrap#configuration

**Comment by starryknight64** [comment]
Awesome! Works great. Thanks! :)
