### ISSUE TITLE
grails.resources.processing.enabled=false in development

### ISSUE THREAD

**Issue by aduchate** [joergrech/KickstartWithBootstrap#34]
When I deactivate the resources processing (grails.resources.processing.enabled=false) in order to be able to test my css changes without having to restart the app, the kickstart css resources are not loaded at all. The ones I have defined in my app are OK.

This seems to be linked to the use of less skins definitions: When I force the use of those resources:

'bootstrap' {
            dependsOn 'jquery'
            resource url: [dir: 'bootstrap/js',         file: 'bootstrap.min.js']
            resource url: [dir: 'bootstrap/css',        file: 'bootstrap.css']
            resource url: [dir: 'bootstrap/css',        file: 'bootstrap-responsive.css']
        }
        // TODO: link a second static/compiled skin or remove the switch entries in layouts/Kickstart.gsp and /_menu/_config.gsp
        'bootstrap_skinA'   {
            dependsOn   'jquery'
            resource url: [dir: 'bootstrap/js',         file: 'bootstrap.min.js']
            resource url: [dir: 'bootstrap/css',        file: 'bootstrap.css']
            resource url: [dir: 'bootstrap/css',        file: 'bootstrap-responsive.css']
        }

Everything works fine.

Not sure why the less css is used in development and not in production.

**Comment by joergrech** [comment]
If you stop the resource processing the less generation stops too as this is based on the resource plugin. So in dev mode you won't get anything and in prod you get the CSS files. But I will make a check and use the CSS if resources are disabled and you are in dev mode.

The reason for using the css instead of less files in prod was that if you deploy your production system on a PAAS such as Cloudfoundry the time to generate the css files/bundles takes too long and the system will not start. Sadly I cannot access the last compiled css files when in production.

**Comment by aduchate** [comment]
Thanks. I have added the following test but it is deprecated and I am 
not sure it is possible to do it without using the deprecated method in 
kickstart-with-bootstrap-0.9.1/grails-app/conf/KickstartResources.groovy

```
 if (grails.util.Environment.current == 
```

grails.util.Environment.PRODUCTION || 
!org.codehaus.groovy.grails.commons.ConfigurationHolder.config.grails.resources.processing.enabled) 
{

Cheers,
A.

> Jörg Rech mailto:notifications@github.com
> 22 février 2013 11:01
> 
> If you stop the resource processing the less generation stops too as 
> this is based on the resource plugin. So in dev mode you won't get 
> anything and in prod you get the CSS files. But I will make a check 
> and use the CSS if resources are disabled and you are in dev mode.
> 
> The reason for using the css instead of less files in prod was that if 
> you deploy your production system on a PAAS such as Cloudfoundry the 
> time to generate the css files/bundles takes too long and the system 
> will not start. Sadly I cannot access the last compiled css files when 
> in production.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/joergrech/KickstartWithBootstrap/issues/34#issuecomment-13936063. 

## 

_Antoine Duchâteau_
Managing Director
Email : ad@taktik.be mailto:ad@taktik.be
GSM : +32 499 534 536

---

_TAKTIK SA_
Parc de l'Alliance
Avenue de Finlande 8
1420 Braine l'Alleud
Tel : +32 2 333.58.40
Fax : +32 2 648.16.53
http://www.taktik.be/http://www.taktik.be

**Comment by joergrech** [comment]
Hi, thanks. If you like you can check if it works in 0.9.2. I just uploaded it to the Grails plugin repository.

**Comment by omadruga** [comment]
Just got hit by this. Deployed my app to cloudfoundry and it hangs... Disabling the less resources did the trick. 
Perhaps adding a info on the plugin page?

**Comment by joergrech** [comment]
The conditional code in KickstartResources.groovy should do the trick
