### ISSUE TITLE
Versions 0.9.0 and 0.9.2 incompatible with grails 2.1.3

### ISSUE THREAD

**Issue by jabelardo** [joergrech/KickstartWithBootstrap#35]
when I try to install the plugin I get the following error:

Error Plugin hibernate-2.2.0 requires version [2.2 > *] of Grails which your current Grails installation does not meet. Please try install a different version of the plugin or Grails.

**Comment by joergrech** [comment]
Can you check the version defined in your BuildConfig.groovy file? It should state `runtime ":hibernate:$grailsVersion"`. maybe set it to `runtime ":hibernate:2.1.3"`

Furthermore, please look into application.properties: the setting `app.grails.version` should state 2.1.3 in your case.

**Comment by jabelardo** [comment]
it's a clean new project. the BuildConfig.groovy says runtime ":hibernate:$grailsVersion" and  application.properties app.grails.version=2.1.3.

I tried also with runtime ":hibernate:2.1.3" in BuildConfig.groovy

Any way I keep geting Error Plugin hibernate-2.2.0 requires version [2.2 > *] of Grails which your current Grails installation does not meet. Please try install a different version of the plugin or Grails.

I also tested 0.9.2 and got the same results.  But 0.8.x installs just fine

**Comment by joergrech** [comment]
It looks like that the definition in the plugin's BuildConfig is too high. You could try to edit it in ~/.grails/2.1.3/<yourProject>/plugins/kickstart.../grails-app/config/BuildConfig.groovy.

I will look later if I can remove the dependency or the version number.

**Comment by joergrech** [comment]
Please try 0.9.3 - I tested it with Grails 2.1.3 and it works for me now.

**Comment by jabelardo** [comment]
Yes it worked fine! Thanks for this
