### ISSUE TITLE
how to delete demopage, dbdoc and home controller?

### ISSUE THREAD

**Issue by ghost** [joergrech/KickstartWithBootstrap#37]
Hi, I've installed kickstartWithBootstrap and it works fine but I don't need demopage, dbdoc and home.
There is a way to delete them?

**Comment by joergrech** [comment]
That should be relatively easy. The views (demopage and home) are copied into your project - you can just delete them from your project and adapt the URLmappings.groovy in your conf directory (e.g., changing "/" to point to a view index.gsp and redirecting the demopage controller "/demopage/$action?/$id?" to home or a 404 page).

The dbdoc controller is an artefact of Grails - but you can hide it by redirecting it as the demopage.
