### ISSUE TITLE
Pure grails 2.0 support

### ISSUE THREAD

**Issue by trygvea** [joergrech/KickstartWithBootstrap#4]
I would love to see a version based on pure grails 2.0 scaffolding templates and support for the resource framework. 
And I think the plugin would benefit a lot if it is kept simpler. Adding filters, changing UrlMappings, changing the way _form.gsp works etc. should be adressed elsewhere, I think.

**Comment by kimifoud** [comment]
+1

**Comment by joergrech** [comment]
I hope the latest version (0.6.1) helps with the Grails 2.0 conformness. Regarding the diverse "add-ons": I like to see the Kickstart plugin as a fast way to start a project, e.g., for a Startup Weekend. If you only need the Bootstrap functionality have a look at the Twitter-Bootstrap plugin (http://grails.org/plugin/twitter-bootstrap). 
Then again I'm working on an App Configurator where one can configure which parts are to be included and that injects glue-code to make a runnable system.
