### ISSUE TITLE
kickstart.js does not work with jQuery.noConflict()

### ISSUE THREAD

**Issue by ptah23** [joergrech/KickstartWithBootstrap#41]
Hi
In my project I am using a Prototype.js based modal dialog plugin. In order to get this to work jQuery has to be in no conflict mode which means it won't be accessible via '$' but will only be available as 'jQuery'.
To enable the kickstart.js to work in this case you need to wrap your call to $(document.ready) in a function call that has $ as parameter and immediately call the function, passing it jQuery:
(function($) {
   $(document.ready(function(){
//code here 
}));
}(jQuery);

The code inside function($) can then use $ to refer to jQuery.
You can see examples of this pattern in the Bootstap javascript.

**Comment by joergrech** [comment]
If you are still interested please send me the reference to the bootstrap section. I tried to wrap the javascript in kickstart.js but if I do the code will not be executed anymore.
