### ISSUE TITLE
Unable to get the right national flag for zh_CN

### ISSUE THREAD

**Issue by xuqingxin** [joergrech/KickstartWithBootstrap#43]
I'm a Chinese and my locale is zh_CN. When the application starts, I get an error message in console.
| Error 2013-08-15 10:24:13,945 [http-bio-8080-exec-4] ERROR resource.ResourceMeta  - Resource not found: /plugins/kickstart-with-bootstrap-0.9.6/images/flags/zh.png

I find that there's only cn.png under /plugins/kickstart-with-bootstrap-0.9.6/images/flags.

**Comment by joergrech** [comment]
Hi Qingxin,
  if the cn.png is the right flag you can copy it into your project in the
directory /web-app/images/flags and rename it to zh.png : Kickstart uses
the Language parameter to guess the Flag and might not always be correct.

Best regards,
Joerg

2013/8/15 Qingxin Xu notifications@github.com

> I'm a Chinese and my locale is zh_CN. When the application starts, I get
> an error message in console.
> | Error 2013-08-15 10:24:13,945 [http-bio-8080-exec-4] ERROR
> resource.ResourceMeta - Resource not found:
> /plugins/kickstart-with-bootstrap-0.9.6/images/flags/zh.png
> 
> I find that there's only cn.png under
> /plugins/kickstart-with-bootstrap-0.9.6/images/flags.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joergrech/KickstartWithBootstrap/issues/43
> .

## 

_Dr. Jörg Rech_
Freelancer
Web | Mobile | Cloud | Agile
Kriegsstr. 164
76133 Karlsruhe, Germany

I'm a software engineer from Germany working as a freelancer in the IT
sector and interested in the startup scene, building lean startups,
developing new interesting software, and conducting empirical research. My
expertise focusses on the topics Web, Mobile, Cloud, and Agile. More
information can be found at:

Web:  http://www.joerg-rech.com
Twitter:  http://twitter.com/joergrech
Xing: http://www.xing.com/profile/Joerg_Rech/
LinkedIn: http://www.linkedin.com/in/joergrech

**Comment by xuqingxin** [comment]
Hi joergrech,

You solution can work well.

However, would you please do some change to codes, say check the locale, if there's a "_", then the flag file name is second part of the "_"; otherwise, the flag file name is just the locale string. Thus "zh_cn" will result in "cn.png".

I think it'll be better than just renaming cn.png into zh.png. Because it can resolve all locale problems with "_".

Qingxin Xu

**Comment by joergrech** [comment]
Bulk close
