### ISSUE TITLE
Upgrade Bootstrap to 3.0?

### ISSUE THREAD

**Issue by rasheedamir** [joergrech/KickstartWithBootstrap#46]
Do you plan to upgrade to latest version of Bootstrap?

**Comment by joergrech** [comment]
Hi,
  currently, I do not have the time to update the kickstart plugin. Maybe
in the next weeks.

Sorry,
Joerg

2013/9/6 rasheedamir notifications@github.com

> Do you plan to upgrade to latest version of Bootstrap?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joergrech/KickstartWithBootstrap/issues/46
> .

## 

_Dr. Jörg Rech_
Freelancer
Web | Mobile | Cloud | Agile
Kriegsstr. 164
76133 Karlsruhe, Germany

I'm a software engineer from Germany working as a freelancer in the IT
sector and interested in the startup scene, building lean startups,
developing new interesting software, and conducting empirical research. My
expertise focusses on the topics Web, Mobile, Cloud, and Agile. More
information can be found at:

Web:  http://www.joerg-rech.com
Twitter:  http://twitter.com/joergrech
Xing: http://www.xing.com/profile/Joerg_Rech/
LinkedIn: http://www.linkedin.com/in/joergrech

**Comment by rasheedamir** [comment]
Thanks for quick response Joerg. I can help you to upgrade if you can provide guidance!

Also another question that how can I apply different bootstrap theme? Lets say I want to use some theme from this website http://bootswatch.com/? What I have to do to use it?

**Comment by rasheedamir** [comment]
Hello Joerg,

It will be very helpful if you can answer my this question:

"Also another question that how can I apply different bootstrap theme? Lets say I want to use some theme from this website http://bootswatch.com/? What I have to do to use it?"

Thanks in advance.

Regards,
Rasheed

**Comment by joergrech** [comment]
Hi Rasheed,
  to use another Bootstrap theme you need to copy the less and css files
into a directory in your project, build a Resource package similar to the
ones in KickstartResources.groovy (within my plugin: you can find it via
eclipse or in your .grails directory), and then use this resource bundle in
the main.gsp layout file.
Your bundle with the Bootstrap variant should look like this (I'm not 100%
sure if the dummy is still required or if the that was fixed):

```
    'bootstrap2' {
        dependsOn   'jquery'
        resource url: [dir: 'bootstrap2/js',    file:
```

'bootstrap.min.js']
            resource url: [dir: 'bootstrap2',        file: 'bootstrap.less']
            resource url: [dir: 'bootstrap2',        file:
'responsive.less']
            resource url: [dir: 'bootstrap2',        file: 'variables.less']
            resource url: [dir: 'bootstrap2',        file:
'bootswatch.less']
            resource url: "less/dummy.css" // empty css: see
https://github.com/paulfairless/grails-lesscss-resources/issues/25
        }

Best regards,
Joerg

2013/9/9 rasheedamir notifications@github.com

> Thanks for quick response Joerg. I can help you to upgrade if you can
> provide guidance!
> 
> Also another question that how can I apply different bootstrap theme? Lets
> say I want to use some theme from this website http://bootswatch.com/?
> What I have to do to use it?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joergrech/KickstartWithBootstrap/issues/46#issuecomment-24095683
> .

## 

_Dr. Jörg Rech_
Freelancer
Web | Mobile | Cloud | Agile
Kriegsstr. 164
76133 Karlsruhe, Germany

I'm a software engineer from Germany working as a freelancer in the IT
sector and interested in the startup scene, building lean startups,
developing new interesting software, and conducting empirical research. My
expertise focusses on the topics Web, Mobile, Cloud, and Agile. More
information can be found at:

Web:  http://www.joerg-rech.com
Twitter:  http://twitter.com/joergrech
Xing: http://www.xing.com/profile/Joerg_Rech/
LinkedIn: http://www.linkedin.com/in/joergrech

**Comment by rasheedamir** [comment]
Thanks Goerg; I will give it a try and let you know.

**Comment by joergrech** [comment]
Kickstart uses now Bootsrtrap 3.0.3 (since version 1.1.0)
