### ISSUE TITLE
plugins/resources-1.2/src/java" does not exist! 

### ISSUE THREAD

**Issue by colameo** [joergrech/KickstartWithBootstrap#47]
Hi,

I just tried to install ":kickstart-with-bootstrap:0.9.6" on grails 2.2.4 but I get this exception:

| Error Fatal error during compilation org.apache.tools.ant.BuildException: srcdir "/Volumes/hdd2/Users/devusr/.grails/2.2.4/projects/Kickstart1/plugins/resources-1.2/src/java" does not exist! (Use --stacktrace to see the full trace)
| Error org.codehaus.groovy.grails.cli.ScriptExitException
| Error     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
| Error     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
| Error     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
| Error     at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
| Error     at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
| Error     at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
| Error     at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)

Is this plugin compatible with 2.2.4?

Regards
Serano

**Comment by colameo** [comment]
...btw, I just tried with another new project and I get his exception now:

Loading Grails 2.2.4
| Configuring classpath.
| Environment set to development.....
| Installing zip kickstart-with-bootstrap-0.9.6.zip.....
| Installed plugin kickstart-with-bootstrap-0.9.6
| To install Kickstart run the script 'kickstart' (e.g., on command line 'grails kickstart')!
| Installing zip lesscss-resources-1.3.1.zip.....
| Installed plugin lesscss-resources-1.3.1...
| Installing zip font-awesome-resources-3.0.zip.....
| Installed plugin font-awesome-resources-3.0....
| Installing zip resources-1.1.6.zip.....
| Installed plugin resources-1.1.6.....
| Error Fatal error during compilation org.apache.tools.ant.BuildException: srcdir "/Volumes/hdd2/Users/serano/.grails/2.2.4/projects/TestKB1/plugins/resources-1.2/grails-app/resourceMappers" does not exist! (Use --stacktrace to see the full trace)
| Error org.codehaus.groovy.grails.cli.ScriptExitException
| Error     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
| Error     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
| Error     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
| Error     at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
| Error     at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)

**Comment by colameo** [comment]
...ok, with grails 2.3.0 everything works fine!

/Serano

**Comment by joergrech** [comment]
Maybe the problem was a conflict with resource plugin 1.2 and 1.1.6 (I used the older one). It should now work with Grails 2.2.4, but I'm surprised that it works for you with Grails 2.3 - I had some problems because of the big changes in Grails2.3 (Scaffolding, data binding, etc.).
