### ISSUE TITLE
Navbar brand alignment

### ISSUE THREAD

**Issue by martinswanson** [joergrech/KickstartWithBootstrap#5]
The brand does not align with other items in the navbar due to a bug in the kickstart.css 

Current:
.navbar .brand          { padding: 2px 20px 10px 20px; }

Should change to:
.navbar .brand          { padding: 7px 20px 10px 20px; }

**Comment by joergrech** [comment]
Sorry for the late answer. Can you tell me which browser you used when you had this problem? At least on Firefox and Chrome it looks good (better than with 7px top padding).
