### ISSUE TITLE
Datepicker broken on grails 2.3.0

### ISSUE THREAD

**Issue by lucacervasio** [joergrech/KickstartWithBootstrap#51]
I'm using 0.9.6 and upgraded an app to grails 2.3.0, I managed to use jquery 1.8.3 as 1.10 is not working.

Datepicker is broken and dates are not parsed. Maybe new data binding in grails 2.3.0 ?

**Comment by joergrech** [comment]
The datepicker should work now (version 1.1.0) on a web page - however I still have problems with the date binding that was changed in Grails 2.3. jQuery must now be set in the project and you can, e.g., use version 1.10.2.2 of the jQuery plugin.
