### ISSUE TITLE
How to add additional params in the pagination tag?

### ISSUE THREAD

**Issue by xuqingxin** [joergrech/KickstartWithBootstrap#52]
Hi joergrech,

I have a search page for some domain. I hope the pagination can embed additional params, say keyword for query, in the pagination url.

For example, the key is "test", I hope the url be something like http://XXX/domain/search?q=test&max=10&offset=20 for page 3.

I tried &lt;bs:paginate q="test" total="${domainInstanceTotal}" /&gt;, but it doesn't work, only generates url like http://XXX/domain/search?max=10&offset=20, missing the additional param.

**Comment by starryknight64** [comment]
Try this:

`<bs:paginate params="${[q: 'test', total: domainInstanceTotal]}" />`

**Comment by xuqingxin** [comment]
Hi starryknight64,

I've tried your way, but it failed with the following message:

Error 500    Error processing GroovyPageView: Tag [paginate] is missing required attribute [total]

**Comment by starryknight64** [comment]
Sorry, try putting total as an actual paginate attribute:

`<bs:paginate total="${domainInstanceTotal}" params="${[q: 'test']}" />`

**Comment by xuqingxin** [comment]
It works. Thank you very much!
