### ISSUE TITLE
Bootstrap CSS not applied when i deploy to Tomcat 6 and 7 on Openshift PaaS

### ISSUE THREAD

**Issue by nabiltntn** [joergrech/KickstartWithBootstrap#53]
Hi,

i am deploying my Grails application on openshift cloud which provides Tomcat 6 and 7.
The application deploys and starts fine but when i display the page , the page doesn't look like it's expected ( Boostrap style and classes are not applied ).
I checked the head to verify if all css are there and it seems that's OK.
I am not sure, but i suspect the Less process.

**Comment by joergrech** [comment]
I can not reproduce your problem. It looks like a problem of the PAAS or a problem associated with the resources plugin. You might want to check all *Resources.groovy files in the conf directory of your project and the kickstart plugin. Maybe some bundles are handled differently in dev and prod environments.
