### ISSUE TITLE
jQuery conflict

### ISSUE THREAD

**Issue by madeupname** [joergrech/KickstartWithBootstrap#55]
I see you have updated the plugin to use Bootstrap 3.0.2. This requires jQuery 1.9 or greater as seen here:

https://github.com/twbs/bootstrap/blob/v3.0.2/bower.json

which was referenced here:

http://getbootstrap.com/getting-started/#whats-included

I added to BuildConfig:

runtime ":jquery:1.10.2"

to take care of this. However, when combined with Kickstart:

compile ":kickstart-with-bootstrap:0.9.9"

I get an error during compilation:

| Installing zip jquery-1.8.3.zip.....
| Installed plugin jquery-1.8.3.....
| Error Fatal error during compilation org.apache.tools.ant.BuildException: srcdir "C:\Users\phil.grails\2.2.4\projects\test-grails-224\plugins\jquery-1.10.2\grails-app\taglib" does not exist! (Use --stacktrace to see the full trace)

It appears there's a hard dependency on jQuery 1.8.3, which according to the Bootstrap authors is incompatible. I'm not sure if there's a way to specify a dependency in Grails in terms of a minimum level (in this case 1.9), but that would be best. Otherwise, maybe leave out the dependency and instruct users to add it themselves like Spring Security UI does.

For reference, I'm using Grails 2.2.4 and testing with a brand new project generated by GGTS 3.4.

**Comment by joergrech** [comment]
The current version 1.1.0 now refers to jquery but has no dependency to a jquery plugin - The project including the Kickstart plugin must define the version to use (and a fresh Grails project currently does refer to 1.10.2.2).
