### ISSUE TITLE
Plugin kickstart-with-bootstrap-0.9.9 requires version [2.0 > * > 2.3] of Grails.

### ISSUE THREAD

**Issue by ghost** [joergrech/KickstartWithBootstrap#56]
I'm using grails-2.3.3 but when I try to install the plugin I have the error.

Plugin kickstart-with-bootstrap-0.9.9 requires version [2.0 > \* > 2.3] of Grails which your current Grails installation does not meet. Please try install a different version of the plugin or Grails.

**Comment by joergrech** [comment]
Hi, Kickstart is not yet ready for Grails 2.3

**Comment by fernandopolti** [comment]
When it will be ready? I will love to add this to my new project.
Thank youj!
