### ISSUE TITLE
Register modal form: display issues 

### ISSUE THREAD

**Issue by eloudsa** [joergrech/KickstartWithBootstrap#57]
Hello

I have set Kickstart on a brand new Grails 2.2.4 projet.
I noticed that when I select "Sign in > Register", the modal form looks weird.
The entry fields and the register button are outside the modal form.

Any idea how to fix that ?

Thanks.

Said

**Comment by joergrech** [comment]
Thanks for the tip, The modal is now fixed (at least since version 1.1.0)
