### ISSUE TITLE
No templates ?

### ISSUE THREAD

**Issue by eloudsa** [joergrech/KickstartWithBootstrap#61]
Hello

I have created a new Grails 2.3.4 project.

I have used the version 1.0.0 of kickstart, refreshed the dependencies and ran "kickstart".

I was surprised to see that no templates have been installed in my project.

In addition, the views added with Spring Security Core (1.2.7.3) have not been replaced by kickstart.

Is it a known issues or did I missed something ?

Thanks

Said

**Comment by snowping** [comment]
Same problem so far. When I generate the views for my domains it uses the basic grails scaffolding templates. Thank you.

**Comment by joergrech** [comment]
Sorry for the inconvenience. The publish-plugin command did not include the template files in the zip that is downloaded by Grails. I have notified the developers of the release plugin and hope to have a solution in the next days. 

Until then I fear you have to download them from the source directory on your own at:
https://github.com/joergrech/KickstartWithBootstrap/tree/master/src/templates

**Comment by eloudsa** [comment]
Thanks @joergrech 

By the way, I've noticed that the auth.gsp et denied.gsp views are not more created by the "kickstart" command.
Is there any reason for that ?

Regards.

**Comment by snowping** [comment]
@joergrech Thank you, it was very helpful. Kind regards

**Comment by joergrech** [comment]
@eloudsa I'm not sure were on the update path I lost the spring-security gsps but I have them on my computer and will include them in the next version.

**Comment by eloudsa** [comment]
Thanks @joergrech ;-)

**Comment by bartoleo** [comment]
there is a 'hypotehical' release date for this fix and https://github.com/joergrech/KickstartWithBootstrap/pull/67 ?

thanks

Leo

**Comment by joergrech** [comment]
The templates are now (version 1.1.0) includes in the plugin's zip file.

**Comment by bartoleo** [comment]
thank you!

2014-01-26 Jörg Rech notifications@github.com

> The templates are now (version 1.1.0) includes in the plugin's zip file.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joergrech/KickstartWithBootstrap/issues/61#issuecomment-33318124
> .

## 

Leo Bartoloni
B.M.E.

Via Gabotto, 13 - 12042 Bra (Cn) - Italy
Tel. +39 0172 476929

## Web Site www.bmeweb.it

Qualsiasi utilizzo non autorizzato del presente messaggio e dei suoi
allegati è vietato e potrebbe costituire reato.
Se lei avesse ricevuto erroneamente questo messaggio, Le saremmo grati se
provvedesse alla distruzione dello stesso
e degli eventuali allegati.
Opinioni, conclusioni o altre informazioni riportate nella e-mail, che non
siano relative alle attività e/o
alla missione aziendale di B.M.E. si intendono non attribuibili alla
società stessa, né la impegnano in alcun modo.
