### ISSUE TITLE
Error: Script 'Kickstart' not found, did you mean:

### ISSUE THREAD

**Issue by sophie-nilgren** [joergrech/KickstartWithBootstrap#63]
Hi,

I am a beginner of programmin and also Groovy/Grails. Now I have installed a Grails 2.3.4 version and Groovy/Grails Tool Suite Version: 3.4.0 .

Now I am trying to install a Kickstart plug-in and I did set a dependency in BuildConfig.groovy like this: compile ": kickstart-with-bootstrap: 1.0.0" 

However when I trying to call the script "kickstart" I get an error message:

Loading Grails 2.3.4
|Configuring classpath
|Running pre-compiled script

|Script 'Kickstart' not found, did you mean:
   1) Stats
   2) DbmListLocks
   3) TestApp
   4) DbmClearChecksums
   5) War
Please make a selection or enter Q to quit: 

Am I calling the script correctly or what might be the error reason?

Kind regards,

Sophie

**Comment by joergrech** [comment]
Hi Sophie,
  you probably have to load the plugin first by calling "grails clean" or
"grails compile" on the command line. Grails does not yet know that you
have changed the BuildConfig.groovy and does not yet know of the kickstart
script.

Please note that there is a small bug in the plugin in such a way that the
scaffolding templates were not included in the zip file. Therefore, you
will not be able to generate new GSPs based on Bootstrap. Please see the
issue #61 (https://github.com/joergrech/KickstartWithBootstrap/issues/61)
for the current state. I will probably update the plugin in a couple of
days.

Best regards,
Joerg

2013/12/18 sophie-nilgren notifications@github.com

> Hi,
> 
> I am a beginner of programmin and also Groovy/Grails. Now I have installed
> a Grails 2.3.4 version and Groovy/Grails Tool Suite Version: 3.4.0 .
> 
> Now I am trying to install a Kickstart plug-in and I did set a dependency
> in BuildConfig.groovy like this: compile ": kickstart-with-bootstrap:
> 1.0.0"
> 
> However when I trying to call the script "kickstart" I get an error
> message:
> 
> Loading Grails 2.3.4
> |Configuring classpath
> |Running pre-compiled script
> 
> |Script 'Kickstart' not found, did you mean:
> 1) Stats
> 2) DbmListLocks
> 3) TestApp
> 4) DbmClearChecksums
> 5) War
> Please make a selection or enter Q to quit:
> 
> Am I calling the script correctly or what might be the error reason?
> 
> Kind regards,
> 
> Sophie
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joergrech/KickstartWithBootstrap/issues/63
> .

## 

_Dr. Jörg Rech_
Freelancer / Software Engineer
Web | Mobile | Cloud | Agile | Portals
Kriegsstr. 164
76133 Karlsruhe, Germany

I'm a software engineer from Germany working as a freelancer in the IT
sector and interested in the startup scene, building lean startups, and
developing new interesting software. More information can be found at:

Web:  http://www.joerg-rech.com
Twitter:  http://twitter.com/joergrech
Xing: http://www.xing.com/profile/Joerg_Rech/
LinkedIn: http://www.linkedin.com/in/joergrech

**Comment by sophie-nilgren** [comment]
Hi,

Combination of "grails clean" and "grails compile" helped. Thanks about fast reply and help!

Br,

Sophie
