### ISSUE TITLE
Scaffolding incorrectly handles fields marked as non displayable.

### ISSUE THREAD

**Issue by stlhrt** [joergrech/KickstartWithBootstrap#65]
This is the same bug as present in https://github.com/grails-plugins/grails-scaffolding plugin.
I provided a fix for this to original grails plugin via pull request which was marged a few days ago https://github.com/grails-plugins/grails-scaffolding/pull/9

**Comment by joergrech** [comment]
Many thanks, I integrated your changes into version 1.1.0.
