### ISSUE TITLE
Resource loading issue?

### ISSUE THREAD

**Issue by magicboo** [joergrech/KickstartWithBootstrap#68]
<b>Situation</b>:
1. Add a simple JS chart (http://www.highcharts.com/stock/demo/basic-line) into GSP with "kickstart" layout have javascript error
2. Add "_debugResources=y" to the URL (still with "kickstart" layout), the chart display normally (and all kickstart style are missing, as expect)
3. Change the layout to "main" (without debug parameter), the chart display normally

<b>Javascript Error in console</b>:

<pre>
"Uncaught TypeError: Object [object Object] has no method 'highcharts'
(anonymous function)
c                                               bundle-bundle_bootstrap_defer.js:4
p.fireWith                                   bundle-bundle_bootstrap_defer.js:4
k                                               bundle-bundle_bootstrap_defer.js:6
n.onload.n.onreadystatechange    bundle-bundle_bootstrap_defer.js:6
</pre>

<b>Steps</b>:
1. Add js resource in ApplicationResources.groovy

<pre>
    - modules = { application {
        dependsOn 'jquery'
        resource url:'js/application.js'
        resource url:'js/highstock.js', disposition: 'head'
        resource url:'js/exporting.js', disposition: 'head'
    }}
</pre>
1. The page: 
   <pre>
   &lt;head&gt;
       &lt;meta name="layout" content="kickstart" /&gt;
       &lt;r:require modules="application"/&gt;
   &lt;/head&gt;
   &lt;body&gt;
       &lt;div id="container" style="height: 500px; min-width: 500px"/&gt;
       &lt;r:script&gt;...sample scripts that call highcharts....&lt;/r:script/&gt;
   &lt;/body&gt;
   </pre>

**Comment by magicboo** [comment]
Update: If I remark the line 
<b>resource url: [dir: 'bootstrap/js/tests/vendor',file: 'jquery.js']</b>
and unmark 
<b>dependsOn 'jquery'</b>
in KickstartResources.groovy, my chart can be display correctly....but I don't know why!

**Comment by joergrech** [comment]
Sorry, I cannot reproduce that problem I assume that it is connected with the jQuery 1.8 problem or the lesscss/resource plugin. If you have the time please test with version 1.1.0 of Kickstart in a new project - it uses jQuery 1.10 via the project's dependency (the plugin does not have the dependency anymore).

**Comment by magicboo** [comment]
Congratulation on the 1.1.0!
But...my problem still happen in 1.1.0 and I don't know how to fix it now because you added jquery module requirement in the template already but not in the KickstartResources.gorrvy....=(

Here are my steps (in more detail), hope that you can reproduce the problem:
(The sample can be referred from /Highstock-1.3.7/examples/candlestick/index.htm)
1. **Create new project and apply 1.1.0**
2. **Modify ApplicationResources.groovy to add highstock JS files**
   ![image](https://f.cloud.github.com/assets/1650387/2010753/cca5df0c-8771-11e3-9a2a-abdfa7c44f0a.png)
3. **Add a page stock.gsp in view/home/stock.gsp**
   ![image](https://f.cloud.github.com/assets/1650387/2010768/f4c91d50-8771-11e3-9ead-75a1e5cb871b.png)
4. **Add a line "/stock"        (view:"/home/stock") in UrlMappings.groovy**
5. **Put related JS file in place (\web-app\js...) (Sorry that I can't attach related files here)**
6. **Browse to http://localhost:8080/InvestmentLab/stock**
   ![image](https://f.cloud.github.com/assets/1650387/2010826/e15f5bc0-8772-11e3-9ae7-4bf174b0b264.png)
7. **The error is:**
   ![image](https://f.cloud.github.com/assets/1650387/2010837/0241ccba-8773-11e3-9bb4-367b07bece7e.png)
8. **Add "_debugResources=y" can see the chart**
   ![image](https://f.cloud.github.com/assets/1650387/2010854/3cb834c4-8773-11e3-946b-3acdb6c6d2b0.png)

**Comment by magicboo** [comment]
Update again:
I remark the following line in KickstartResources.groovy and the javascript chart can show correctly!
**resource url: [dir: 'bootstrap/js/tests/vendor',file: 'jquery.js']**
