### ISSUE TITLE
Style alert-error not defined in Bootstrap3 (should be alert-danger)

### ISSUE THREAD

**Issue by bartoleo** [joergrech/KickstartWithBootstrap#69]
Bootstrap3 style for 'error' alerts is alert-danger (in Bootstrap2 it was alert-error')

**Comment by joergrech** [comment]
Thanks for the tip! I integrated the change in version 1.1.0

**Comment by bartoleo** [comment]
thank you

2014-01-26 Jörg Rech notifications@github.com

> Closed #69 https://github.com/joergrech/KickstartWithBootstrap/issues/69
> .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joergrech/KickstartWithBootstrap/issues/69
> .

## 

Leo Bartoloni
B.M.E.

Via Gabotto, 13 - 12042 Bra (Cn) - Italy
Tel. +39 0172 476929

## Web Site www.bmeweb.it

Qualsiasi utilizzo non autorizzato del presente messaggio e dei suoi
allegati è vietato e potrebbe costituire reato.
Se lei avesse ricevuto erroneamente questo messaggio, Le saremmo grati se
provvedesse alla distruzione dello stesso
e degli eventuali allegati.
Opinioni, conclusioni o altre informazioni riportate nella e-mail, che non
siano relative alle attività e/o
alla missione aziendale di B.M.E. si intendono non attribuibili alla
società stessa, né la impegnano in alcun modo.
