### ISSUE TITLE
ccsrewrite fails after spring security is added to project causing glyphicons to disappear.

### ISSUE THREAD

**Issue by pbb6w7** [joergrech/KickstartWithBootstrap#77]
Hello, 
I absolutely love the way this plug in is put together! Great plugin!

I ran into the following issue. I installed this plug in and got the basic site running. Next I set out to configure security using the spring security plug in. After installing the security plug in (with the appropriate configurations) when I start up the application the logs show this:
WARN  mapper.cssrewriter  - Cannot resolve CSS resource, leaving link as is: resource:/bootstrap/dist/fonts/glyphicons-halflings-regular.eot
WARN  mapper.cssrewriter  - Cannot resolve CSS resource, leaving link as is: resource:/bootstrap/dist/fonts/glyphicons-halflings-regular.eot?#iefix
WARN  mapper.cssrewriter  - Cannot resolve CSS resource, leaving link as is: resource:/bootstrap/dist/fonts/glyphicons-halflings-regular.woff
WARN  mapper.cssrewriter  - Cannot resolve CSS resource, leaving link as is: resource:/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf
WARN  mapper.cssrewriter  - Cannot resolve CSS resource, leaving link as is: resource:/bootstrap/dist/fonts/glyphicons-halflings-regular.svg#glyphicons-halflingsregular201

The fallout seems to be that when viewing the website using an external browser (not from inside eclipse) all the glyphicons do not load and display instead as a small square. Interestingly enough if I use eclipse's build in browser everything displays properly. 

Here are current defined plugins:
plugins {
        // plugins for the build system only
        build ":tomcat:7.0.47"

```
    // plugins for the compile step
    compile ":scaffolding:2.0.1"
    compile ":cache:1.1.1"
    compile ":kickstart-with-bootstrap:1.1.0"
    compile ":lesscss-resources:1.3.3"

    // plugins needed at runtime but not for compilation
    runtime ":hibernate:3.6.10.4" // or ":hibernate4:4.1.11.4"
    runtime ":database-migration:1.3.8"
    runtime ":jquery:1.10.2"
    runtime ":spring-security-core:2.0-RC2"
    runtime ":kickstart-with-bootstrap:1.1.0"
    runtime ":resources:1.2.6"
    runtime ":lesscss-resources:1.3.3"
    // Uncomment these (or add new ones) to enable additional resources capabilities
    //runtime ":zipped-resources:1.0.1"
    //runtime ":cached-resources:1.1"
    //runtime ":yui-minify-resources:0.1.5"
}
```

Any ideas would be greatly appreciated. Thank you in advance.

**Comment by pbb6w7** [comment]
Got a crude workaround for this. Downloaded the 4 glyphicon files and put them directly under the web-app/css folder. Then in my main.css file included these lines and it started working again:
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url('glyphicons-halflings-regular.eot');
  src: url('glyphicons-halflings-regular.eot?#iefix') format('embedded- opentype'), url('glyphicons-halflings-regular.woff') format('woff'), url('glyphicons-halflings-regular.ttf') format('truetype'), url('glyphicons-halflings-regular.svg#glyphicons-halflingsregular') format('svg');
}

**Comment by fstiffo** [comment]
It seems that the glyphicons works only with resources:1.2.1 adn security core 1.2.7.3 any version greater than this breaks the links

**Comment by pbb6w7** [comment]
Thanks Francesco, reverted back to resources:1.2.1 and all is good. Will go ahead and close this issue since this does not seem to be related to the kickstart plugin itself.
