### ISSUE TITLE
How to modify plugin's source code and apply to grails in 2.3.6

### ISSUE THREAD

**Issue by xuqingxin** [joergrech/KickstartWithBootstrap#88]
I'm using Grails 2.3.6 and KickstartWithBootstrap 1.1.0. After I added
compile ":kickstart-with-bootstrap:1.1.0"
in BuildConfig.groovy, I found plugin related files downloaded to C:\Users\XXX.m2\repository\org\grails\plugins\kickstart-with-bootstrap\1.1.0.

Now I want to do some modification to the originally generated files, such as create.gsp, edit.gsp and _form.gsp for every domain object. But I don't want to modify them manually one by one. Since it's a trivial work, I hope by modifying the plugin source codes a little, the expected files can be generated automatically.

How can I achieve that?

Thanks.
Qingxin Xu

**Comment by psramkumar** [comment]
fork the KickstartWithBootstrap plugin and build you own local plugin, and include in your project

Note: this is a forum Question not an issue Please close.
